### ISSUE TITLE
GIFs don't animate beyond the first page when you scroll

### ISSUE THREAD

**Issue by dotcommer** [darsain/chrome-dribbblehd#4]
When the first couple rows load in, any gifs that happen to be in there animate, but as you scroll down to view more, those gifs that load in do not animate.  This issue just showed up with the new layout (switching from pages to an infinite scroll format).

Chrome:  Version 43.0.2357.132
OS:  Mac OSX 10.9.5

**Comment by dotcommer** [comment]
Also one more thing I'm noticing:  Images loaded after you scroll down are of lower quality (but same resolution) than the initial few that load at the top.

**Comment by darsain** [comment]
Yeah, dribbble changed how their site works. I'm rewriting this extension atm.

**Comment by dotcommer** [comment]
Cool.  Lookin' forward to the update.  Much appreciated!

**Comment by darsain** [comment]
2.0 has been published and should start arriving in your browsers within an hour.
