### ISSUE TITLE
Dribbble HD does not extend to other pages

### ISSUE THREAD

**Issue by dotcommer** [darsain/chrome-dribbblehd#5]
Dribbble HD doesn't have an effect on other pages of Dribbble aside from the "Popular" section.  If I go to my likes page, the display fall's back to dribbble's style with small squares and rows.

Chrome: Version 43.0.2357.132
OS:  Mac OSX 10.9.5

**Comment by darsain** [comment]
2.0 has been published and should start arriving in your browsers within an hour.

You can now also check in which pages the extension is configured to run by looking at `config.json:paths`(https://github.com/darsain/chrome-dribbblehd/blob/master/config.json) property.

Other less popular places where extension used to run (search results, lists, and buckets) have been scraped. It was a pain to maintain those styles, and I don't think it's a big deal as those pages are almost never visited.

**Comment by dotcommer** [comment]
Thanks for the updates!  They're working great.  Still wish this functionality was carried over to the likes page though.  It would be incredibly useful for those of us who use the likes page as a page of inspiration and resources and want to browse it like the shots page.

**Comment by darsain** [comment]
Huh, didn't know about that page. Not using likes at all :)

Nevertheless, checked it, and it's using old styles. It'd be a pain to make it work there and maintain. If they update that page to use the same styles as any other shots displaying page, it'd be a question of adding a property to `config.json:paths` object to make it work.

**Comment by dotcommer** [comment]
Ah ok.  Well either way, I really appreciate the work you've done to make browsing dribbble a lot nicer.  If you accept donations, please send the link my way.

**Comment by darsain** [comment]
Yah, I have a [support the development](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=23CALWRSTQ8X2
) thingy set up, but I guess I'm bad at plastering it all over the place :)
