### ISSUE TITLE
About 2x Images by Default on Popups

### ISSUE THREAD

**Issue by fatihturan** [darsain/chrome-dribbblehd#7]
Hi,

I really like your extension. But I miss 2x images on shot popups or shot detail page by other Chrome Dribbble extensions. 

So, do you think to add this feature on next version?

Best regards.

**Comment by darsain** [comment]
Shouldn't be that hard to add. When I'll have some time I'll look at it.

**Comment by darsain** [comment]
Since dribble finally added an [option to see big pictures](https://dribbble.com/shots/2245848-Hit-me-with-your-big-shots), this extension is now pointless and I'm deprecating it.
