### ISSUE TITLE
Search Result Wrong View

### ISSUE THREAD

**Issue by fatihturan** [darsain/chrome-dribbblehd#8]
Hi,

There is wrong view of shot on [search results page](https://www.dropbox.com/s/v0ogfdwfr9uq5u2/Screenshot%202015-08-11%2013.39.52.png?dl=0). Can you fix it when you have time?

Best regards.

**Comment by darsain** [comment]
Damn, that shouldn't happen. I'll look into it.

**Comment by darsain** [comment]
Fixed, but I want to finish one more thing before releasing new version. Hopefully today.
